### ISSUE TITLE
Support claims with verifiable resources

### ISSUE THREAD

**Issue by sayakpaul** [sayannath/CoAtNet-GSoC#2]
From the README:

> CoAtNet is considered the State-of-the-Art model for Image Classification.

There are better models than CoAtNet. It's better to avoid claims like that and include more specific statements like below:

> CoAtNet achieves xx.xx% top-1 classification accuracy on the ImageNet-1k dataset (validation split). To know more,  please refer to the original paper [link].

**Comment by sayannath** [comment]
Sure!

**Comment by sayannath** [comment]
> From the README:
> 
> > CoAtNet is considered the State-of-the-Art model for Image Classification.
> 
> There are better models than CoAtNet. It's better to avoid claims like that and include more specific statements like below:
> 
> > CoAtNet achieves xx.xx% top-1 classification accuracy on the ImageNet-1k dataset (validation split). To know more,  please refer to the original paper [link].

Updated

```
CoAtNet achieves 86.0% ImageNet top-1 accuracy; When pre-trained with 13M images from ImageNet-21K, our CoAtNet achieves 88.56% top-1 accuracy, matching ViT-huge pre-trained with 300M images from JFT-300M while using 23x less data; Notably, when we further scale up CoAtNet with JFT-3B, it achieves 90.88% top-1 accuracy on ImageNet
```
